import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Sidebar from "./student-portal/sidebar";
import StudentBanner from "./student-portal/student-banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentPortalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gradient-to-br from-[#F8FAFC] to-[#EFF6FF]">
          <StudentBanner />
          <div className="flex max-w-5xl mx-auto  gap-4">
            <div className="w-[30%] h-screen">
              <Sidebar />
            </div>

            <div className="w-[70%]">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
